name: Run API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build Docker Image
      run: |
        docker build -t simple_api .

    - name: Run Docker Container
      run: |
        docker run -d -p 8000:8000 --name api simple_api

    - name: Wait for API to be ready
      run: |
        until curl --fail http://localhost:8000/ping; do
          echo "Waiting for API to start..."
          sleep 5
        done

    - name: Install Test Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Behave Tests
      run: |
        behave features/

    - name: Stop Docker Container
      if: always()
      run: |
        docker stop api
        docker rm api

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: behave-results
        path: reports/