name: Run Behave Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      fastapi:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
        ports:
          - "8000:80"
        env:
          MODULE_NAME: "app.main"
        options: >-
          --health-cmd="curl --fail http://localhost:8000/ || exit 1"
          --health-interval=15s
          --health-timeout=10s
          --health-retries=10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install behave requests

    - name: Run Behave tests
      run: |
        mkdir -p reports
        behave features/ --junit --junit-directory reports

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: behave-results
        path: reports/