name: Run API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      api:
        build:
          context: .
        ports:
          - "8000:8000"
        options: >-
          --health-cmd="curl --fail http://localhost:8000/ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Behave tests
      run: |
        behave features/

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: behave-results
        path: reports/